name: Compile and Deploy Website

on:
    push:
        paths:
            - "docs/**"
            - "website/**"
            - ".github/workflows/website.yml" # If we change this build script, it should rerun
            - "bonnie.toml" # Any changes to the `deploy-prod` command should trigger a rebuild
            - "tribble.yml" # Any changes to hte contributing docs should update this
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # The website builder accesses Git history for old examples, so we need everything
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: cargo install bonnie wasm-pack
            - run: cargo install perseus-cli --version 0.4.0-beta.5
            - run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo install tribble
            - run: npm install -g tailwindcss
            - run: npm install
              working-directory: website
            - name: Build website
              run: bonnie site deploy-prod
            - name: Deploy website to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: website/pkg
                  publish_branch: gh-pages
